# Generated by Django 2.2.12 on 2020-06-03 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('webhook_url', models.CharField(max_length=500)),
                ('enabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signalpings.WebHook')),
            ],
        ),
    ]
