# Generated by Django 2.2.13 on 2020-06-25 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signalpings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupsignal',
            options={'verbose_name': 'Group Signal', 'verbose_name_plural': 'Group Signals'},
        ),
        migrations.AlterModelOptions(
            name='webhook',
            options={'verbose_name': 'Webhook', 'verbose_name_plural': 'Webhooks'},
        ),
        migrations.CreateModel(
            name='TimerSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignore_past_timers', models.BooleanField(default=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signalpings.WebHook')),
            ],
            options={
                'verbose_name': 'Timer Board Signal',
                'verbose_name_plural': 'Timer Board Signals',
            },
        ),
        migrations.CreateModel(
            name='FleetSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignore_past_fleets', models.BooleanField(default=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signalpings.WebHook')),
            ],
            options={
                'verbose_name': 'Fleet Signal',
                'verbose_name_plural': 'Fleet Signals',
            },
        ),
    ]
