# Generated by Django 2.2.13 on 2020-07-03 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0012_index_additions'),
        ('signalpings', '0002_auto_20200625_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRAppSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCorporationInfo')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signalpings.WebHook')),
            ],
            options={
                'verbose_name': 'HR Application Signal',
                'verbose_name_plural': 'HR Application Signals',
            },
        ),
    ]
