# Generated by Django 2.2.12 on 2020-07-04 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0012_index_additions'),
        ('signalpings', '0003_hrappsignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='timersignal',
            name='corporation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCorporationInfo'),
        ),
    ]
