# Generated by Django 3.1.1 on 2020-09-24 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalpings', '0005_charactersignal_statesignal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRPSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_type', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=8)),
                ('mention_requestor', models.BooleanField(default=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signalpings.webhook')),
            ],
            options={
                'verbose_name': 'SRP Signal',
                'verbose_name_plural': 'SRP Signals',
            },
        ),
    ]
