# Generated by Django 3.1.3 on 2020-12-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalpings', '0006_srpsignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrappsignal',
            name='notify_comments',
            field=models.BooleanField(default=True),
        ),
    ]
